on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
jobs:
  reusable_workflow_job:
    name: Test Reuse
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello ${{ inputs.username }}"
