on:
  push:

jobs:
  call-workflow:
    name: Build Images
    uses: seanshahkarami/actions/.github/workflows/example.yml@main
    with:
      username: robot
  call-workflow-again:
    name: Run Tests
    uses: seanshahkarami/actions/.github/workflows/example.yml@main
    with:
      username: bingbong
  call-workflow-final:
    name: Setup Docs
    uses: seanshahkarami/actions/.github/workflows/example.yml@main
    with:
      username: wilson
  build:
    uses: seanshahkarami/actions/.github/workflows/go.yml@main
    with:
      go-version: "^1.19"
