on:
  push:

jobs:
  call-workflow:
    name: Build Images
    uses: ./workflows/example.yml@main
    with:
      username: robot
  call-workflow-again:
    name: Run Tests
    uses: seanshahkarami/workflows/.github/workflows/example.yml@main
    with:
      username: bingbong
  call-workflow-final:
    name: Setup Docs
    uses: seanshahkarami/workflows/.github/workflows/example.yml@main
    with:
      username: wilson
