on:
  push:

jobs:
  call-workflow:
    name: Build Images
    uses: seanshahkarami/common/.github/workflows/example.yml
    with:
      username: robot
  call-workflow-again:
    name: Run Tests
    uses: seanshahkarami/common/.github/workflows/example.yml
    with:
      username: bingbong
  call-workflow-final:
    name: Setup Docs
    uses: seanshahkarami/common/.github/workflows/example.yml
    with:
      username: wilson
